services:
  - type: web
    name: Zoom Meeting SDK Auth
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/chrisdeveloperit/zoom.auth
    rootDir: .
    plan: free
    envVars:
      - key: ZOOM_MEETING_SDK_KEY
        sync: false
      - key: ZOOM_MEETING_SDK_SECRET
        sync: false
