name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          ZOOM_MEETING_SDK_KEY: ${{ secrets.ZOOM_MEETING_SDK_KEY }}
          ZOOM_MEETING_SDK_SECRET: ${{ secrets.ZOOM_MEETING_SDK_SECRET }}
        run: npm run build

      - name: Zip the application
        run: zip -r deploy.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: zauth
          environment_name: Zauth-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
