name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          ZOOM_MEETING_SDK_KEY: ${{ secrets.ZOOM_MEETING_SDK_KEY }}
          ZOOM_MEETING_SDK_SECRET: ${{ secrets.ZOOM_MEETING_SDK_SECRET }}
        run: npm run release

      - name: Zip the application
        run: zip -r deploy.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'zauth'
          environment_name: 'Zauth-env'
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
      - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: GitHub Actions - Deploy to Elastic Beanstalk Failed
          to: your-email@example.com
          from: github-actions@example.com
          body: The deployment to Elastic Beanstalk has failed. Please check the logs for more details.